### ISSUE TITLE
MVP Demo-ready Checklist

### ISSUE THREAD

**Issue by bezi** [TheOscars2/FoodApp#1]
Only check off a screen when it is completely polished and implemented for MVP, i.e. when we complete this page we have completed the MVP!

- [x] 1) #18 Recipe View
![screen 1](https://user-images.githubusercontent.com/1945397/42735002-e04cc30a-8801-11e8-8af4-51bc34f4173c.jpg)

- [x] 2) #19  Recipe Detail View
![screen 2](https://user-images.githubusercontent.com/1945397/42735098-868e273a-8803-11e8-91b9-fc043ba56cf3.jpg)

- [x] 3) Recipe Creation
![screen 3](https://user-images.githubusercontent.com/1945397/42735107-9c891202-8803-11e8-9e24-86e8c1b22af9.jpg)

- [x] 4) Food Input View
![screen 4](https://user-images.githubusercontent.com/1945397/42735108-9c9b67c2-8803-11e8-858f-cf5817c22d42.jpg)

- [x] 5)  Produce Code Input
![screen 5](https://user-images.githubusercontent.com/1945397/42735109-9caf9f30-8803-11e8-92af-52cd29bcdcce.jpg)

- [x] 6) Produce Code Loading
![screen 6](https://user-images.githubusercontent.com/1945397/42735110-9cc30188-8803-11e8-8a5f-ce00afddbdb2.jpg)

- [x] 7) Manual Entry Screen
![screen 7](https://user-images.githubusercontent.com/1945397/42735111-9cd56260-8803-11e8-956e-4bc222aaf021.jpg)

- [x] 8) Barcode Entry Screen
![screen 8](https://user-images.githubusercontent.com/1945397/42735112-9ce9b2ba-8803-11e8-8d44-b1131b96f169.jpg)

- [x] 9) "Fridge" View
![screen 9](https://user-images.githubusercontent.com/1945397/42735113-9cfc40e2-8803-11e8-8d58-00dcfb59f61a.jpg)

- [x] 10) Food Detail View
![screen 10](https://user-images.githubusercontent.com/1945397/42735115-9d0f4ebc-8803-11e8-9984-295a54dba06d.jpg)
